### ISSUE TITLE
Question about Android audio only

### ISSUE THREAD

**Issue by dinki** [AlexxIT/StreamAssist#12]
First off, this is super impressive and very close to what I'm wanting to use.  I'm working on making a replacement for my Echo Show devices by using an Android tablet.   fixtSE made a [video](https://www.youtube.com/watch?v=fP_BNFWLYnk) featuring your StreamAssist and in it he demos it with Android.   I'd absolutely love to use this if it could be used as an Android audio input device.  I am already using the camera on the device with Fully Kiosk for motion detect and am pretty sure that the IPCAM software and the Fully Kiosk can't use the same camera device.

Is it possible to use StreamAssist but only use the mic on the tablet and leave the camera available to Fully Kiosk?

Thanks!

**Comment by AlexxIT** [comment]
This is software problem. StreamAssist requests only audio from RTSP source. It don't needs any video.
Maybe you should search another Android software. Or start to use only IPCAM as video source from Android.
Fully Kiosk streams video in the MJPEG format. It can't have audio inside.

**Comment by relust** [comment]
I am working on a similar project but also with visual support. I have a [demo](https://www.youtube.com/watch?v=EcL6o62Vnoo&t=33s) .
I managed to replace the esp32 satellite that I used in this demo with Stream Assist integration together with the android application [IP Webcam(https://play.google.com/store/apps/details?id=com.pas.webcam&hl=en_AU).
This application has the option to send only audio and thus I managed to use the camera on the fully kiosk browser to detect movement and, at the same time, the IP Webcam application to send audio and it works very well together.
I hope that AlexxIT manages to find a solution to this [problem](https://github.com/AlexxIT/StreamAssist/issues/11) and then integrate everything in the Stream Assist integration, that is, I want to put the visual part in the Stream Assist integration as well.

**Comment by tbrasser** [comment]
Install IP Webcam and use that instead of FKB motion detection (I run them through frigate and switch screen/screensaver based on that)

Works great in tandem!

**Comment by dinki** [comment]
> I am working on a similar project but also with visual support. I have a [demo](https://www.youtube.com/watch?v=EcL6o62Vnoo&t=33s) . I managed to replace the esp32 satellite that I used in this demo with Stream Assist integration together with the android application [IP Webcam](https://play.google.com/store/apps/details?id=com.pas.webcam&hl=en_AU). This application has the option to send only audio and thus I managed to use the camera on the fully kiosk browser for motion detection, at the same time, the IP Webcam application to send audio and it works very well together. 

Thanks to you all for the responses.  This gives me great encouragement that what I'm wanting to do is possible.  I installed Web IPCAM and configured it.  I can see and hear audio using the tablet's http server page at port 8080.  I cannot, however, get StreamAssist to recognize the wake word so I'm not sure that the audio is getting into StreamAssist properly.  @relust Could you possibly share any relevant settings in Web IPCAM that I should be setting and also what url you are using in the StreamAssist integration? I've tried http and the rtsp://192.168.0.152:8080/h264_ulaw.sdp urls without success.

**Comment by relust** [comment]
It works for me with rtsp://192.168.0.247:8080/h264_pcm.sdp and with rtsp://192.168.0.247:8080/h264_ulaw.sdp with video and audio enabled. In version 1 of the stream assist integration, it worked very well with the Audio only option activated, but I just noticed that now, with version 2 of the Stream Assist integration, it no longer works. Maybe AlexxIT can tell us why it no longer works with version 2 of the integration.

**Comment by dinki** [comment]
Thanks @relust I have it working now.  I ended up having to get out of FK totally and got IP Webcam running then I fired up FK and things are working pretty well.  I had been trying with audio only so turning video on seems to have done the trick.  I did notice that if I have music playing via Music Assistant that the music does not resume after Assist answers.  Other than that, fantastic!  Thanks for the help.

I do notice a second or so of lag when saying the wake word before I get the notice it is listening.  I'm wondering if this is because of the additional overhead of the video being streamed too.   Would certainly think the audio only stream would be ideal.

**Comment by relust** [comment]
I added the tablet camera to the frigate and now I have a motion sensor, person detection and even facial detection and I can make an automation to turn on and off the tablet screen like the fully kiosk browser did. You can set to send the answers from Assist on the media player from the tablet via fully kiosk browser or browser mod.
On Google speakers, if a tts is sent or a response is played, if something is played on the speaker, the music does not resume. That's why it would be good to use google speakers for music and for Assist responses the media player on the tablet or other Home Assistant satellites.

**Comment by dinki** [comment]
@relust   I see what you mean but I am trying to have everything self contained if possible.  I'm trying to replace my Alexa/Google devices :)

Do you have a way to auto start IP Webcam server?  Is that a feature of pro?

**Comment by relust** [comment]
In Power management I checked "Stream on device boot", then in "Optional permissions" I checked "Allow streaming in background". I start the server only once and then let it run in the background. If the tablet is restarted, IP Webcam starts by itself and with the server running.

**Comment by tbrasser** [comment]
Media not resuming is because music assistant doesn't support announcements/tts yet.
