### ISSUE TITLE
normal increase in CPU by 40% and RAM by 10%? rpi4 8gb

### ISSUE THREAD

**Issue by sebax80** [AlexxIT/StreamAssist#18]
after following this guide https://fixtse.com/blog/stream-assist I noticed a large increase in CPU and RAM, is this normal? rpi4 8gb

![immagine](https://github.com/AlexxIT/StreamAssist/assets/64022736/3013837d-018a-48e2-ad14-29a24785b5ae)

![immagine](https://github.com/AlexxIT/StreamAssist/assets/64022736/9b0551cb-1cd2-475b-8288-422a0127922b)

![immagine](https://github.com/AlexxIT/StreamAssist/assets/64022736/4265772b-4c53-4c1b-9fb1-94c7a8193ecb)

**Comment by AlexxIT** [comment]
Probably yes. You can test Assistant via browser (without this component) and compare.
