### ISSUE TITLE
Question: Works with Google Nest Battery Cam?

### ISSUE THREAD

**Issue by sayam93** [AlexxIT/StreamAssist#23]
Would this work for a google nest cam battery 2nd generation (given the limitations of how sdm api works)?

If not, could I use a Wyoming Satellite (https://www.youtube.com/watch?v=eTKgc0YDCwE) as an audio input?

P.S. I am using Home Assistant cloud for stt and tts and have open wakeword running on the satellite device (not on the same device as my home assistant installation).

**Comment by AlexxIT** [comment]
I have no idea
