### ISSUE TITLE
RuntimeError: Detected that custom integration 'stream_assist' calls async_write_ha_state from a thread

### ISSUE THREAD

**Issue by mterry63** [AlexxIT/StreamAssist#28]
Home Assistant 2024.5.3 logging error:  RuntimeError: Detected that custom integration 'stream_assist' calls async_write_ha_state from a thread at custom_components/stream_assist/sensor.py, line 47: self.async_write_ha_state(). Please report it to the author of the 'stream_assist' custom integration.

Reading about this: It’s likely not a thread safe application, which recently (2024.4.x) is causing HA to crash after the full conversion to python 3.12.
You should check it with this process: [Discord 40](https://discord.com/channels/330944238910963714/332167321311510530/1229625706351300618).
It is in the general channel of the HA Discord and will tell you if this is integration is writing unsafe thread writes.

I think it’s just updating the async_write_ha_state() to schedule_update_ha_state() since it’s not in an async function.

**Comment by jshtz4** [comment]
I included a fix for this in PR #26

**Comment by AlexxIT** [comment]
https://github.com/AlexxIT/StreamAssist/releases/tag/v2.1.0
