### ISSUE TITLE
Wake Word detection response not working

### ISSUE THREAD

**Issue by DevGoran** [AlexxIT/StreamAssist#39]
Wake word detection response is not working. I've tried with one response and multiple, however, it does not work. Response to my command work. Any idea why?

**Comment by AlexxIT** [comment]
I don't think the problem is related to this integration. The problem is somewhere with pipeline and the Hass configuration

**Comment by lexiismadd** [comment]
I have the same issue. I can't get the wake word detection to work. The only time I can make it work is when I play back a file or video clip of a US accent saying the words ok nabu. But when I say it myself, it doesn't pick it up.
I also noticed that the stream assist device isn't listed in the Assists section of the Voice Assistant menu in haos

**Comment by DevGoran** [comment]
For me it turned out that the tts language for wake word detection caused the issue. The example in the conifg was rather confusing but now it works.

**Comment by lexiismadd** [comment]
> For me it turned out that the tts language for wake word detection caused the issue. The example in the conifg was rather confusing but now it works.

Are you able to elaborate on what you changed in your config to make. It work for you?

**Comment by loryanstrant** [comment]
Would also be curious to know what you did, as I can't get it to work. :-(

**Comment by DevGoran** [comment]
For me, it was really just the format for the language. en_US&voice=en_US-joe-medium made it work.

**Comment by lexiismadd** [comment]
> For me, it was really just the format for the language. en_US&voice=en_US-joe-medium made it work.

Where did you change it?

**Comment by DevGoran** [comment]
In the configuration of the the integration itself

**Comment by loryanstrant** [comment]
Any chance you can share a screenshot please?
