### ISSUE TITLE
STT, target is not populated

### ISSUE THREAD

**Issue by rfam13** [AlexxIT/StreamAssist#9]
Hello, thanks for taking the time to create this.

I have run into one issue, when the response comes back and TTS is triggered to play on a media device it does not play.  I have configured it for a media player, but when I check the logs, I see that the command sent had no target devices even though I have selected one.  Is this correct to expect the device to be here?

Thanks!

![SmartSelect_20240217_030836_Home Assistant](https://github.com/AlexxIT/StreamAssist/assets/98683384/a85fbac7-39d1-4f08-afae-44c194a69e21)

**Comment by AlexxIT** [comment]
Show your STT attributes.

**Comment by rfam13** [comment]
My mistake, it looks like it is just Alexa devices that are not playing.  Adding my soundbar worked right away.

Thanks!
